title:  Jumail.co
author: Jumail Mohamed
email: Jumaelmohamed@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the blog of Jumail Mohamed

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jumail.co"
github_username:  jumaeel

paginate: 5
excerpt_separator: <!-- MORE -->

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

global_styles: /assets/css/main.css
meta:
  - about
