title:  blog.willbadart.com
author: Will Badart
email: wbadart@live.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the blog of <a href="https://willbadart.com" target="_blank">Will Badart<i class="fa fa-external-link"></i></a>.
cclicense: by-nc

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.willbadart.com"
github_username:  wbadart

paginate: 5
excerpt_separator: <!-- MORE -->

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

global_styles: /assets/css/main.css
meta:
  - about
